### ISSUE TITLE
where to find help

### ISSUE THREAD

**Issue by atredennick** [atredennick/esa_data_viz_2015#2]
Add a slide or two on where to find help (stackoverflow, ggplot help pages, ggplot google list, etc). Also, "how to google a problem".

**Comment by atredennick** [comment]
Added two slides at the end on ggplo2 help pages and stackoverflow (see 80bf81c). Look good @naupaka ?

**Comment by naupaka** [comment]
Looks great. I think this is plenty to talk about. Thanks!

**Comment by atredennick** [comment]
Cool.
